# Generated by Django 3.0.7 on 2020-06-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20200604_1700'),
        ('student', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='University_Names',
            new_name='University_Name',
        ),
        migrations.AlterModelOptions(
            name='place_type',
            options={'verbose_name_plural': 'Place Types'},
        ),
        migrations.AlterModelOptions(
            name='university_name',
            options={'verbose_name_plural': 'University Names'},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
