# Generated by Django 3.0.7 on 2020-06-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='type_of_place',
        ),
    ]
