# Generated by Django 3.0.8 on 2020-07-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20200628_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='http_ref',
            field=models.URLField(default='http://pandemap.com'),
            preserve_default=False,
        ),
    ]
